[pytest]
markers =
    ci_mini: Keep the mark
    regression: Run regression cases
    sanity: Run sanitycase
    gcuSanity: Run sanity testing
    gcuStress: Run stress testing
    gcuSmoke: Run smoke testing
    pt20600 : Run torch2.6 testing
