import glob
import os
import stat
import re
import shutil
import subprocess
import sys
import traceback
import platform
import pathlib

# Disable autoloading before running 'import torch' to avoid circular dependencies
os.environ["TORCH_DEVICE_BACKEND_AUTOLOAD"] = "0"

import torch

import distutils.ccompiler
import distutils.command.clean
from sysconfig import get_python_version
from distutils.version import LooseVersion
from distutils.command.build_py import build_py
from setuptools.command.build_ext import build_ext
from setuptools.command.install import install
from setuptools import setup, distutils, Extension
from setuptools.command.build_clib import build_clib
from setuptools.command.egg_info import egg_info
from setuptools.command.sdist import sdist
from wheel.bdist_wheel import bdist_wheel

# from torch.utils.cpp_extension import CppExtension  # pylint: disable=C0411

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

TARGET_BUILD_DIR = os.getenv("TARGET_BUILD_DIR", default="build")

CMAKE_GENERATOR = os.getenv("CMAKE_GENERATOR", default="Unix Makefiles")
GENERATOR_CLI = {"Unix Makefiles": "make", "Ninja": "ninja"}


def get_torch_version():
    try:
        return re.split(r"^([0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}).*", torch.__version__)[1]
    except:
        _, _, exc_traceback = sys.exc_info()
        frame_summary = traceback.extract_tb(exc_traceback)[-1]
        return os.path.dirname(frame_summary.filename)


def get_torch_abi():
    abi_flag = getattr(torch._C, "_PYBIND11_BUILD_ABI", None)
    if abi_flag and abi_flag.startswith("_cxxabi"):
        return abi_flag[-2:]
    # guess abi from compiler of pytorch by existing abi rule.
    # gcc 11 == abi 16
    # gcc 12 == abi 17
    # gcc 13 == abi 18
    # ...
    # generally, new abi format should be compatiable to old.
    m = re.search(r"GCC\s+(\d+)\.\d*", torch.__config__.show())
    if m:
        gcc_major = int(m.group(1))
        return str(gcc_major + 5)
    return "0"


def get_torch_supa_git_head_sha(base_dir) -> str:
    if not pathlib.Path(".git").exists():
        return "N/A"

    torch_supa_git_sha = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=base_dir).decode("ascii").strip()
    return torch_supa_git_sha[:7]


def get_torch_git_head_sha() -> str:
    return torch.version.git_version


def is_torch_use_isa_enabled() -> bool:
    return os.getenv("TORCH_USE_ISA", default="").upper() in ["ON", "1", "YES", "TRUE", "Y"]


def get_build_version() -> str:
    local_version_label = "br2xx"
    if is_torch_use_isa_enabled():
        local_version_label += ".isa"
    build_mode = get_build_mode()
    version = os.getenv("TORCH_SUPA_VERSION", default="1.0.0")
    torch_versions = [int(v) for v in get_torch_version().split(".")]
    torch_version = torch_versions[0] * 10000 + torch_versions[1] * 100 + torch_versions[2]
    if build_mode != "sdist":
        version += f".{torch_version}"
        full_version_specifiers = r"{}+{}".format(version, local_version_label)
    build_type = get_build_type()
    if (build_type == "Debug" or build_mode == "sdist") and pathlib.Path(".git").exists():
        try:
            full_version_specifiers = version + "+" + "git" + get_torch_supa_git_head_sha(BASE_DIR)
        except:
            pass
    return full_version_specifiers


def update_file_if_change(filepath: str, content: str):
    exist_content = ""
    if os.path.exists(filepath):
        with open(filepath, "r") as fi:
            exist_content = fi.read()
    if exist_content != content:
        with open(filepath, "w") as fo:
            fo.write(content)

def get_supa_version():
    with open(os.path.join(os.environ.get("SUPA_PATH", "/usr/local/birensupa/sdk/latest/supa"), "version.txt")) as fi:
        return fi.read().strip()

def get_cuda_version():
    with open(os.path.join(os.getenv("SUDA_CUDA_HOME"), "include", "cuda.h")) as fi:
        for line in fi:
            m = re.match(r"#define\s+CUDA_VERSION\s+(\d+)", line)
            if m:
                cuda_version = int(m.group(1))
                return f"{cuda_version // 1000}.{cuda_version % 1000 // 10}"
    raise RuntimeError("CUDA_VERSION not found in cuda.h. make sure suda is active.")

def create_version_files():
    torch_supa_version = get_build_version()
    torch_git_sha = get_torch_git_head_sha()
    torch_supa_git_sha = get_torch_supa_git_head_sha(BASE_DIR)

    py_version = f"""
# Autogenerated file, do not edit!
__version__ = '{torch_supa_version}'
__torch_supa_gitrev__ = '{torch_supa_git_sha}'
__torch_gitrev__ = '{torch_git_sha}'
__build_type__ = '{get_build_type()}'
__supa_version__ = '{get_supa_version()}'
__cuda_version__ = '{get_cuda_version()}'"""

    update_file_if_change(os.path.join(pathlib.Path(BASE_DIR), "torch_supa", "version.py"), py_version)


def is_native_op_enabled():
    return os.getenv("BUILD_NATIVE_OP", default="0").upper() in ["ON", "1", "YES", "TRUE", "Y"]


def which(thefile):
    path = os.environ.get("PATH", os.defpath).split(os.pathsep)
    for d in path:
        fname = os.path.join(d, thefile)
        fnames = [fname]
        if sys.platform == "win32":
            exts = os.environ.get("PATHEXT", "").split(os.pathsep)
            fnames += [fname + ext for ext in exts]
        for name in fnames:
            if os.access(name, os.F_OK | os.X_OK) and not os.path.isdir(name):
                return name
    return None


def get_cmake_command():
    def _get_version(cmd):
        for line in subprocess.check_output([cmd, "--version"]).decode("utf-8").split("\n"):
            if "version" in line:
                return LooseVersion(line.strip().split(" ")[2])
        raise RuntimeError("no version found")

    "Returns cmake command."
    cmake_command = "cmake"
    if platform.system() == "Windows":
        return cmake_command
    cmake3 = which("cmake3")
    cmake = which("cmake")
    if cmake3 is not None and _get_version(cmake3) >= LooseVersion("3.12.0"):
        cmake_command = "cmake3"
        return cmake_command
    elif cmake is not None and _get_version(cmake) >= LooseVersion("3.12.0"):
        return cmake_command
    else:
        raise RuntimeError("no cmake or cmake3 with version >= 3.12.0 found")


def get_build_type():
    build_type = "Release"
    if os.getenv("DEBUG", default="0").upper() in ["ON", "1", "YES", "TRUE", "Y"]:
        build_type = "Debug"

    if os.getenv("REL_WITH_DEB_INFO", default="0").upper() in ["ON", "1", "YES", "TRUE", "Y"]:
        build_type = "RelWithDebInfo"

    return build_type


def get_build_mode():
    for i in range(1, len(sys.argv)):
        if not sys.argv[i].startswith("-"):
            return sys.argv[i]

    raise RuntimeError("Run setup.py without build mode.")


def get_pytorch_dir():
    try:
        import torch

        return os.path.dirname(os.path.abspath(torch.__file__))
    except Exception:
        _, _, exc_traceback = sys.exc_info()
        frame_summary = traceback.extract_tb(exc_traceback)[-1]
        return os.path.dirname(frame_summary.filename)


def generate_bindings_code(base_dir):
    generate_code_cmd = ["bash", os.path.join(base_dir, "script", "generate_code.sh"), sys.executable, get_torch_version()]
    if subprocess.call(generate_code_cmd) != 0:  # Compliant
        print("Failed to generate ATEN bindings: {}".format(generate_code_cmd), file=sys.stderr)
        sys.exit(1)


def CppExtension(name, sources, *args, **kwargs):
    r"""
    Creates a :class:`setuptools.Extension` for C++.
    """
    pytorch_dir = get_pytorch_dir()
    temp_include_dirs = kwargs.get("include_dirs", [])
    temp_include_dirs.append(os.path.join(pytorch_dir, "include"))
    kwargs["include_dirs"] = temp_include_dirs

    temp_library_dirs = kwargs.get("library_dirs", [])
    temp_library_dirs.append(os.path.join(pytorch_dir, "lib"))
    kwargs["library_dirs"] = temp_library_dirs

    libraries = kwargs.get("libraries", [])
    libraries.append("c10")
    libraries.append("torch")
    libraries.append("torch_cpu")
    libraries.append("torch_python")
    libraries.append("torch_supa")
    kwargs["libraries"] = libraries
    kwargs["language"] = "c++"
    return Extension(name, sources, *args, **kwargs)


class Clean(distutils.command.clean.clean):

    def run(self):
        f_ignore = open(".gitignore", "r")
        ignores = f_ignore.read()
        pat = re.compile(r"^#( BEGIN NOT-CLEAN-FILES)?")
        clean_flag = True
        filename_list = []
        for wildcard in filter(None, ignores.split("\n")):
            match = pat.match(wildcard)
            if match:
                # Ignore lines which begin with '#'.
                # Ignore files exist only at end of .gitignore
                if match.group(1):
                    clean_flag = False
                    continue
            for filename in glob.glob(wildcard):
                if clean_flag:
                    filename_list.append(filename)
                else:
                    if filename in filename_list:
                        filename_list.remove(filename)
        f_ignore.close()
        for f in filename_list:
            if pathlib.Path(f).is_file():
                os.remove(f)
            else:
                shutil.rmtree(f, ignore_errors=False)

        build_dir = os.path.join(BASE_DIR, f"{TARGET_BUILD_DIR}")
        if pathlib.Path(build_dir).exists():
            shutil.rmtree(build_dir)
        else:
            distutils.command.clean.clean.run(self)

        if CLEAN_TORCH_SUPA_OP:
            SUBMODULE_DIR = os.path.join(BASE_DIR, "third-party/torch-supa-op")
            print(f"Clean torch-supa using its setup.py: {SUBMODULE_DIR}")
            subprocess.check_call(
                ["python3", "setup.py", "clean"],
                cwd=SUBMODULE_DIR
            )



class CPPLibBuild(build_clib, object):
    def run(self):
        cmake = get_cmake_command()

        if cmake is None:
            raise RuntimeError(
                "CMake must be installed to build the following extensions: "
                + ", ".join(e.name for e in self.extensions)
            )
        self.cmake = cmake

        build_dir = os.path.join(BASE_DIR, f"{TARGET_BUILD_DIR}")
        build_type_dir = os.path.join(build_dir, get_build_type())
        output_lib_path = os.path.join(build_type_dir, "packages/torch_supa/lib")
        os.makedirs(build_type_dir, exist_ok=True)
        os.makedirs(output_lib_path, exist_ok=True)
        self.build_lib = os.path.relpath(os.path.join(build_dir, "packages/torch_supa"))
        self.build_temp = os.path.relpath(build_type_dir)
        print(f"{torch._C._GLIBCXX_USE_CXX11_ABI=}, {get_torch_abi()=}", flush=True)
        cmake_args = [
            "-DCMAKE_BUILD_TYPE=" + get_build_type(),
            "-DCMAKE_INSTALL_PREFIX=" + os.path.abspath(output_lib_path),
            "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=" + os.path.abspath(output_lib_path),
            "-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=" + os.path.abspath(output_lib_path),
            "-DTORCH_SUPA_INSTALL_LIBDIR=" + os.path.abspath(output_lib_path),
            "-DPYTHON_EXECUTABLE=" + sys.executable,
            "-DPYTORCH_INSTALL_DIR=" + get_pytorch_dir(),
            "-DPYTORCH_REL_VERSION=" + get_build_version(),
            "-DTORCH_ABI_VER=" + get_torch_abi(),
            "-DPYTORCH_BUILD_CONFIG=" + torch.__config__.show().splitlines()[-1],
            "-DBR_BUILD_NATIVE_OP=" + ("ON" if is_native_op_enabled() else "OFF"),
            "-DUSE_KINETO=" + ("ON" if USE_KINETO else "OFF"),
            "-DUSE_SPLIT_SUPA=" + ("ON" if USE_SPLIT_SUPA else "OFF"),
            "-DUSE_MAVX512_CPU_ALL_REDUCE=" + ("ON" if USE_MAVX512_CPU_ALL_REDUCE else "OFF"),
            "-DBRCC_ENABLE_DEBUGGING_OPTIONS=" + ("ON" if BRCC_ENABLE_DEBUGGING_OPTIONS else "OFF"),
            "-DUSE_PING_PONG=" + ("ON" if USE_PING_PONG else "OFF"),
            "-DUSE_PARALLEL_COMPILE=" + ("ON" if USE_PARALLEL_COMPILE else "OFF"),
            "-DENABLE_COVERAGE=" + ("ON" if ENABLE_COVERAGE else "OFF"),
            "-DENABLE_PERF_TOOLS=" + ("ON" if ENABLE_PERF_TOOLS else "OFF"),
            "-DTORCH_SUPA_OP_DIR=" + os.getenv("TORCH_SUPA_OP_DIR", default="OFF"),
            "-DUSE_FLASH_ATTENTION=" + ("ON" if USE_FLASH_ATTENTION else "OFF"),
            "-D_GLIBCXX_USE_CXX11_ABI=" + str(int(torch._C._GLIBCXX_USE_CXX11_ABI)),
            "-G" + CMAKE_GENERATOR,
        ]

        SUBMODULE_DIR = os.path.join(BASE_DIR, "third-party/torch-supa-op")
        torch_supa_op_dir = os.getenv("TORCH_SUPA_OP_DIR", f"{SUBMODULE_DIR}/torch_supa_op/lib")
        if os.path.exists(os.path.join(torch_supa_op_dir, "libtorch_supa_op.so")):
            cmake_args.append(f"-DTORCH_SUPA_OP_DIR={torch_supa_op_dir}")
        elif os.getenv("TORCH_SUPA_OP_DIR"):
            raise RuntimeError(f"Can not find libtorch_supa_op.so in the given path: {torch_supa_op_dir}")
        else:
            # python3 setup.py build
            print(f"Building torch-supa using its setup.py: {SUBMODULE_DIR}")
            BR_INCLUDE_DIR = os.path.join(BASE_DIR, f"{TARGET_BUILD_DIR}/{get_build_type()}/packages/torch_supa/include")
            submodule_env = os.environ.copy()
            submodule_env.update({"USE_BR_INCLUDE_DIR": BR_INCLUDE_DIR, "USE_PRIVATEUSE1": "ON"})
            subprocess.check_call(
                ["python3", "setup.py", "build"],
                cwd=SUBMODULE_DIR,
                env=submodule_env,
            )
            cmake_args.append(f"-DTORCH_SUPA_OP_DIR={torch_supa_op_dir}")
        self.copy_file(
            os.path.join(torch_supa_op_dir, "libtorch_supa_op.so"),
            os.path.join(TARGET_BUILD_DIR, f"{get_build_type()}/packages/torch_supa/lib/libtorch_supa_op.so"),
        )

        if not WITH_BCCL:
            cmake_args.append("-DUSE_BCCL=OFF")

        build_args = ["-j", f"{MAX_JOBS}"]
        subprocess.check_call([self.cmake, BASE_DIR] + cmake_args, cwd=build_type_dir, env=os.environ)
        subprocess.check_call([GENERATOR_CLI[CMAKE_GENERATOR]] + build_args, cwd=build_type_dir, env=os.environ)


class Build(build_ext, object):

    def run(self):
        self.run_command("build_clib")
        self.build_lib = os.path.relpath(os.path.join(BASE_DIR, f"{TARGET_BUILD_DIR}/{get_build_type()}/packages"))
        self.build_temp = os.path.relpath(os.path.join(BASE_DIR, f"{TARGET_BUILD_DIR}/{get_build_type()}"))
        self.library_dirs.append(
            os.path.relpath(os.path.join(BASE_DIR, f"{TARGET_BUILD_DIR}/{get_build_type()}/packages/torch_supa/lib"))
        )
        super(Build, self).run()


class InstallCmd(install):

    def finalize_options(self) -> None:
        self.build_lib = os.path.relpath(os.path.join(BASE_DIR, f"{TARGET_BUILD_DIR}/{get_build_type()}/packages"))
        return super(InstallCmd, self).finalize_options()


def get_src_py_and_dst():
    ret = []
    generated_python_files = glob.glob(os.path.join(BASE_DIR, "torch_supa", "**/*.py"), recursive=True)
    for src in generated_python_files:
        dst = os.path.join(
            os.path.join(BASE_DIR, f"{TARGET_BUILD_DIR}/{get_build_type()}/packages/torch_supa"),
            os.path.relpath(src, os.path.join(BASE_DIR, "torch_supa")),
        )
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        ret.append((src, dst))

    header_files = [
        "torch_supa/csrc/*.h",
        "torch_supa/csrc/*/*.h",
        "torch_supa/csrc/*/*/*.h",
        "torch_supa/csrc/*/*/*/*.h",
        "torch_supa/csrc/aten/operators/*/*.h",
    ]
    glob_header_files = []
    for regex_pattern in header_files:
        glob_header_files += glob.glob(os.path.join(BASE_DIR, regex_pattern), recursive=True)

    for src in glob_header_files:
        dst = os.path.join(
            os.path.join(BASE_DIR, f"{TARGET_BUILD_DIR}/{get_build_type()}/packages/torch_supa/include/torch_supa"),
            os.path.relpath(src, os.path.join(BASE_DIR, "torch_supa")),
        )
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        ret.append((src, dst))

    torch_header_files = ["*/*.h", "*/*/*.h", "*/*/*/*.h", "*/*/*/*/*.h", "*/*/*/*/*/*.h"]
    torch_glob_header_files = []
    for regex_pattern in torch_header_files:
        torch_glob_header_files += glob.glob(os.path.join(BASE_DIR, "patch/include", regex_pattern), recursive=True)

    for src in torch_glob_header_files:
        dst = os.path.join(
            os.path.join(BASE_DIR, f"{TARGET_BUILD_DIR}/{get_build_type()}/packages/torch_supa/include"),
            os.path.relpath(src, os.path.join(BASE_DIR, "patch/include")),
        )
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        ret.append((src, dst))

    generated_json_files = glob.glob(os.path.join(BASE_DIR, "torch_supa", "**/*.json"), recursive=True)
    for src in generated_json_files:
        dst = os.path.join(
            os.path.join(BASE_DIR, f"{TARGET_BUILD_DIR}/{get_build_type()}/packages/torch_supa"),
            os.path.relpath(src, os.path.join(BASE_DIR, "torch_supa")),
        )
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        ret.append((src, dst))

    cmake_file_src = os.path.join(BASE_DIR, "torch_supa", "cmake/TorchSUPAConfig.cmake")
    cmake_file_dst = os.path.join(
        os.path.join(BASE_DIR, f"{TARGET_BUILD_DIR}/{get_build_type()}/packages/torch_supa"),
        os.path.relpath(cmake_file_src, os.path.join(BASE_DIR, "torch_supa")),
    )
    os.makedirs(os.path.dirname(cmake_file_dst), exist_ok=True)
    ret.append((cmake_file_src, cmake_file_dst))
    return ret


class EggInfoBuild(egg_info, object):
    def finalize_options(self):
        self.egg_base = os.path.relpath(os.path.join(BASE_DIR, f"{TARGET_BUILD_DIR}/{get_build_type()}/packages"))
        ret = get_src_py_and_dst()
        for src, dst in ret:
            self.copy_file(src, dst)
        super(EggInfoBuild, self).finalize_options()


class PythonPackageBuild(build_py, object):
    def run(self) -> None:
        ret = get_src_py_and_dst()
        for src, dst in ret:
            self.copy_file(src, dst)
        super(PythonPackageBuild, self).finalize_options()


class SDistBuild(sdist, object):
    def get_dependencies(self):
        subprocess.run(["git", "submodule", "update", "--init", "--recursive"], check=True, stdout=subprocess.PIPE)

        internal_sudnn_headers = ["sudnn-internal.h", "sudnn-internal_types.h"]

        def copy(src_dir: pathlib.Path, target_dir: pathlib.Path, filename: str):
            if not src_dir.exists():
                print(f"Warning: {src_dir} not found. Please confirm if software stack is installed")
                return

            if not target_dir.exists():
                print(f"Create {target_dir}")
                target_dir.mkdir(parents=True)

            file_path = pathlib.Path(filename)
            src_file_path = src_dir / file_path
            target_file_path = target_dir / file_path

            if not src_file_path.exists():
                print(f"Warning: {src_file_path} not found. Please confirm if software stack is installed.")
                return

            # src_file_path.copy(target_file_path)
            target_file_path.write_text(src_file_path.read_text())

        # copy sudnn internal headers
        source_sudnn_internal_dir = pathlib.Path("/usr/include")
        target_sudnn_internal_dir = pathlib.Path("third-party/biren/sudnn")
        for header in internal_sudnn_headers:
            copy(source_sudnn_internal_dir, target_sudnn_internal_dir, header)

    def run(self) -> None:
        self.get_dependencies()
        super(SDistBuild, self).run()

        third_party_biren_path = pathlib.Path("third-party/biren")
        if third_party_biren_path.exists():
            shutil.rmtree(third_party_biren_path)


def find_dependencies(package_path):
    dependencies = []
    output = subprocess.check_output(["ldd", package_path]).decode("utf-8")
    for line in output.splitlines():
        if "=>" in line:
            dependencies.append(line.split("=>")[0].strip("\t").strip())
    return dependencies


class BdistWheelBuild(bdist_wheel):
    def run(self):
        self.run_command("egg_info")
        bdist_wheel.run(self)

        if USE_AUDITWHEEL:
            include_dependencies = ["libstdc++.so", "libm.so", "libgcc_s.so", "libc.so"]
            build_dir = os.path.join(BASE_DIR, f"{TARGET_BUILD_DIR}")
            build_type_dir = os.path.join(build_dir, get_build_type())
            torch_supa_lib = os.path.join(build_type_dir, "packages/torch_supa/lib/libtorch_supa.so")
            dependencies = find_dependencies(torch_supa_lib)

            file = glob.glob(os.path.join(self.dist_dir, "*linux*.whl"))[0]
            auditwheel_cmd = [
                "python3",
                "-m",
                "auditwheel",
                "repair",
                "--plat",
                "linux_x86_64",
                "-w",
                self.dist_dir,
                file,
            ]
            for name in dependencies:
                idx = name.find(".")
                if name[: idx + 3] not in include_dependencies:
                    auditwheel_cmd += ["--exclude", name]

            subprocess.run(
                ["python3", "-m", "pip", "install", "auditwheel>=5.4.0", "patchelf>=0.14"],
                check=True,
                stdout=subprocess.PIPE,
            )
            subprocess.run(auditwheel_cmd, check=True, stdout=subprocess.PIPE)


def install_hooks():
    source_hook = os.path.join("git-hooks", "pre-commit")
    git_hooks_dir = os.path.join(".git", "hooks")
    target_hook = os.path.join(git_hooks_dir, "pre-commit")
    if not os.path.exists(git_hooks_dir):
        print(f"Error: Directory not found {git_hooks_dir}")
        print("Please ensure you're running this command from the Git repo root")
        return False

    if os.path.exists(target_hook):
        with open(source_hook, "rb") as src, open(target_hook, "rb") as dst:
            if src.read() == dst.read():
                return True
    try:
        shutil.copy2(source_hook, target_hook)
        print(f"Hook file copied: {source_hook} -> {target_hook}")

        st = os.stat(target_hook)
        os.chmod(target_hook, st.st_mode | stat.S_IEXEC)
        print(f"Execute permission added: {target_hook}")
        return True
    except Exception as e:
        print(f"Installation failed: {str(e)}")
        return False


if install_hooks():
    print("Hook installed successfully! Commit messages will be validated on next commit")
else:
    print("Hook installation failed, please check errors")
    sys.exit(1)

build_mode = get_build_mode()
if build_mode not in ['clean']:
    create_version_files()
    # Generate bindings code, including RegisterNPU.cpp & NPUNativeFunctions.h.
    generate_bindings_code(BASE_DIR)

# Setup include directories folders.
include_directories = [
    BASE_DIR,
    os.path.join(BASE_DIR, "patch/include"),
]

extra_link_args = []
def is_affirmative(x):
    return x.upper() in ["ON", "1", "YES", "TRUE", "Y"]

DEBUG = is_affirmative(os.getenv("DEBUG", default=""))
BRCC_ENABLE_DEBUGGING_OPTIONS = is_affirmative(os.getenv("BRCC_ENABLE_DEBUGGING_OPTIONS", default="OFF"))
USE_SPLIT_SUPA = is_affirmative(os.getenv("USE_SPLIT_SUPA", default="ON"))
USE_PING_PONG = is_affirmative(os.getenv("USE_PING_PONG", default="ON"))
USE_KINETO = is_affirmative(os.getenv("USE_KINETO", default="ON"))
USE_FLASH_ATTENTION = is_affirmative(os.getenv("USE_FLASH_ATTENTION", default="ON"))
USE_PARALLEL_COMPILE = is_affirmative(os.getenv("USE_PARALLEL_COMPILE", default=""))
USE_AUDITWHEEL = is_affirmative(os.getenv("USE_AUDITWHEEL", default=""))
ENABLE_COVERAGE = is_affirmative(os.getenv("ENABLE_COVERAGE", default="OFF"))
ENABLE_PERF_TOOLS = is_affirmative(os.getenv("ENABLE_PERF_TOOLS", default="OFF"))
USE_MAVX512_CPU_ALL_REDUCE = is_affirmative(os.getenv("USE_MAVX512_CPU_ALL_REDUCE", default="OFF"))
WITH_BCCL = not is_affirmative(os.getenv("BUILD_WITHOUT_BCCL", default="0"))
CLEAN_TORCH_SUPA_OP = is_affirmative(os.getenv("CLEAN_TORCH_SUPA_OP", default="0"))
MAX_JOBS = os.getenv("MAX_JOBS", default=8)

extra_compile_args = [
    "-std=c++17",
    "-Wno-sign-compare",
    "-Wno-deprecated-declarations",
    "-Wno-return-type",
]

if re.match(r"clang", os.getenv("CC", "")):
    extra_compile_args += [
        "-Wno-macro-redefined",
        "-Wno-return-std-move",
    ]

if DEBUG:
    extra_compile_args += ["-O0", "-g"]
    extra_link_args += ["-O0", "-g", "-Wl,-z,now"]
else:
    extra_compile_args += ["-DNDEBUG"]
    extra_link_args += ["-Wl,-z,now,-s"]

if WITH_BCCL:
    extra_compile_args += ["-DUSE_BCCL"]

library_dirs = [os.path.relpath(os.path.join(BASE_DIR, f"{TARGET_BUILD_DIR}/{get_build_type()}/packages/torch_supa/lib"))]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: POSIX :: Linux",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.12",
]

python_version = get_python_version().replace(".", "")
setup(
    name=os.environ.get("TORCH_SUPA_PACKAGE_NAME", "torch_supa"),
    version=get_build_version(),
    description="Biren GPGPU Plugin for PyTorch"
    + "--> build_metadata:{}".format(os.getenv("BUILD_METADATA", default="no_build_metedata")),
    author="Shanghai Biren Technology Co., Ltd",
    author_email="developer@birentech.com",
    python_requires=">=3",
    classifiers=classifiers,
    packages=["torch_supa"],
    libraries=[("torch_supa", {"sources": list()})],
    package_dir={"": os.path.relpath(os.path.join(BASE_DIR, f"{TARGET_BUILD_DIR}/{get_build_type()}/packages"))},
    license="BSD-3",
    ext_modules=[
        CppExtension(
            "torch_supa._C",
            sources=["torch_supa/csrc/InitSupaBindings.cpp"],
            libraries=["torch_supa"],
            include_dirs=include_directories,
            extra_compile_args=extra_compile_args + ["-fstack-protector-all"],
            library_dirs=library_dirs,
            extra_link_args=extra_link_args + ["-Wl,-rpath,$ORIGIN/lib"],
        ),
    ],
    install_requires=[
        "typing-extensions",
        "fastcore",
        "timedelta",
        "torch==" + get_torch_version(),
    ],
    extras_require={},
    package_data={
        "torch_supa": [
            "*.so",
            "lib/*.so*",
        ],
    },
    cmdclass={
        "build_clib": CPPLibBuild,
        "build_ext": Build,
        "build_py": PythonPackageBuild,
        "bdist_wheel": BdistWheelBuild,
        "egg_info": EggInfoBuild,
        "clean": Clean,
        "install": InstallCmd,
        "sdist": SDistBuild,
    },
    entry_points={
        "torch.backends": [
            "torch_supa = torch_supa:_autoload",
        ],
    },
)
