/* Copyright (C) 2020-2026 Shanghai Biren Technology Co., Ltd. */

/*
 * Copyright (c) 2025 Shanghai Biren Technology Co., Ltd. All rights reserved.
 */

#pragma once

#include <c10/core/DeviceGuard.h>
#include <c10/core/Stream.h>
#include <c10/util/SmallVector.h>
#include <cstdint>
#include <mutex>

#ifdef NO_SUPA_RT_HEADER
typedef void* supaStream_t;
#else
#include <supa_runtime.h>
#endif

#include <torch_supa/csrc/core/supa/SUPAMacros.h>

namespace c10::supa {

static constexpr int max_compile_time_stream_priorities = 4;

class C10_SUPA_API SUPAStream {
 public:
  enum Unchecked { UNCHECKED };

  explicit SUPAStream(c10::Stream stream);
  explicit SUPAStream(Unchecked unchecked, c10::Stream stream) : stream_(stream) {}
  ~SUPAStream() = default;

  SUPAStream(const SUPAStream&) = default;
  SUPAStream(SUPAStream&&) = default;
  SUPAStream& operator=(const SUPAStream&) = default;
  SUPAStream& operator=(SUPAStream&&) = default;
  bool operator==(const SUPAStream& other) const noexcept {
    return unwrap() == other.unwrap();
  }

  bool operator!=(const SUPAStream& other) const noexcept {
    return unwrap() != other.unwrap();
  }

  // Implicit conversion to rtStream_t.
  operator supaStream_t() const {
    return stream();
  }

  // Implicit conversion to pytorch Stream.
  operator c10::Stream() const {
    return unwrap();
  }

  // Used to avoid baking in device type explicitly to Python-side API.
  c10::DeviceType device_type() const {
    return c10::DeviceType::PrivateUse1;
  }

  // Get the NPU device index that this stream is associated with.
  c10::DeviceIndex device_index() const {
    return stream_.device_index();
  }

  // Get the full Device that this stream is associated with. The Device
  // is guaranteed to be a NPU device.
  c10::Device device() const {
    return c10::Device(c10::DeviceType::PrivateUse1, device_index());
  }

  c10::StreamId id() const {
    return stream_.id();
  }

  bool query() const;

  void synchronize() const;

  int priority() const;

  // Explicit conversion to supaStream_t.
  supaStream_t stream() const;

  // Explicit conversion to Stream.
  c10::Stream unwrap() const {
    return stream_;
  }

  /// Reversibly pack a SUPAStream into a struct representation.
  /// Previously the stream's data was packed into a single int64_t,
  /// as it was assumed the fields would not require more than
  /// 64 bits of storage in total.
  /// See https://github.com/pytorch/pytorch/issues/75854
  /// for more information regarding newer platforms that may violate
  /// this assumption.
  ///
  /// The SUPAStream can be unpacked using unpack().
  struct c10::StreamData3 pack3() const {
    return stream_.pack3();
  }

  // Unpack a NPUStream from the 3 fields generated by pack().
  static SUPAStream unpack3(c10::StreamId stream_id, c10::DeviceIndex device_index, c10::DeviceType device_type) {
    return SUPAStream(c10::Stream::unpack3(stream_id, device_index, device_type));
  }

  static std::tuple<int, int> priority_range();

 private:
  c10::Stream stream_;
};

/**
 * Get a new stream from the SUPA stream pool.  You can think of this
 * as "creating" a new stream, but no such creation actually happens;
 * instead, streams are preallocated from the pool and returned in a
 * round-robin fashion.
 *
 * You can request a stream from the high priority pool by setting
 * isHighPriority to true, or a stream for a specific device by setting device
 * (defaulting to the current SUPA stream.)
 *
 * Can requeset a NonBlockingUnsafe mode stream by setting isUnsafe to true,
 * but now, NonBlockingUnsafe stream can only create once per device
 * and can only used by BCCL communicator for GSE/semaphore Barrier
 */
C10_SUPA_API SUPAStream getStreamFromPool(bool isHighPriority = false, DeviceIndex device = -1);
// no default priority to disambiguate overloads
C10_API SUPAStream getStreamFromPool(int priority, DeviceIndex device = -1);

/**
 * Get a SUPAStream from a externally allocated one.
 *
 * This is mainly for interoperability with different libraries where we
 * want to operate on a non-torch allocated stream for data exchange or
 * similar purposes
 */
C10_SUPA_API SUPAStream getStreamFromExternal(supaStream_t ext_stream, c10::DeviceIndex device_index);

/**
 * Get the default SUPA stream, for the passed SUPA device, or for the
 * current device if no device index is passed.  The default stream is
 * where most computation occurs when you aren't explicitly using
 * streams.
 */
C10_SUPA_API SUPAStream getDefaultSUPAStream(c10::DeviceIndex device_index = -1);

/**
 * Get the current SUPA stream, for the passed SUPA device, or for the
 * current device if no device index is passed.  The current SUPA stream
 * will usually be the default SUPA stream for the device, but it may
 * be different if someone called 'setCurrentSupaStream' or used 'StreamGuard'
 * or 'SUPAStreamGuard'.
 */
C10_SUPA_API SUPAStream getCurrentSUPAStream(c10::DeviceIndex device_index = -1);

/**
 * Set the current stream on the device of the passed in stream to be
 * the passed in stream.  Yes, you read that right: this function
 * has *nothing* to do with the current device: it toggles the current
 * stream of the device of the passed stream.
 *
 * Confused?  Avoid using this function; prefer using 'SUPAStreamGuard'
 * instead (which will switch both your current device and current stream in
 * the way you expect, and reset it back to its original state afterwards).
 */
C10_SUPA_API void setCurrentSUPAStream(SUPAStream stream);

C10_SUPA_API std::ostream& operator<<(std::ostream& stream, const SUPAStream& s);
} // namespace c10::supa

namespace std {
template <>
struct hash<c10::supa::SUPAStream> {
  size_t operator()(c10::supa::SUPAStream s) const noexcept {
    return std::hash<c10::Stream>{}(s.unwrap());
  }
};
} // namespace std
