# Copyright (C) 2020-2026 Shanghai Biren Technology Co., Ltd.


if(DEFINED ENV{TORCH_SUPA_INSTALL_PREFIX})
  set(TORCH_SUPA_INSTALL_PREFIX $ENV{TORCH_SUPA_INSTALL_PREFIX})
else()
  get_filename_component(CMAKE_CURRENT_LIST_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
  get_filename_component(TORCH_SUPA_INSTALL_PREFIX "${CMAKE_CURRENT_LIST_DIR}/../" ABSOLUTE)
endif()

set(TORCH_SUPA_INCLUDE_DIRS ${TORCH_SUPA_INSTALL_PREFIX}/include)
list(APPEND TORCH_SUPA_INCLUDE_DIRS ${TORCH_SUPA_INSTALL_PREFIX}/include/torch_supa/csrc/api/include)
set(TORCH_SUPA_LIBRARY_DIRS ${TORCH_SUPA_INSTALL_PREFIX}/lib)
